services:
  - type: web
    name: hosting-render
    repo: https://github.com/jmooring/hosting-render
    runtime: static
    buildCommand: chmod a+x build.sh && ./build.sh
    staticPublishPath: public
    envVars:
      - key: DART_SASS_VERSION
        value: 1.93.2
      - key: GO_VERSION
        value: 1.25.3
      - key: HUGO_VERSION
        value: 0.152.2
      - key: NODE_VERSION
        value: 22.20.0
      - key: TZ
        value: Europe/Oslo
